### ISSUE TITLE
Questions about multiple context, and your other library

### ISSUE THREAD

**Issue by jarlah** [dai-shi/react-context-global-state#5]
Hi

I have some questions. I am currently using react-hooks-global-state and the only reason why is because its so equal to redux. 

Question is. Why do we cling so tight to redux? I mean we shouldnt have to use redux and react redux only because its standard? Are there some limitations to create and use multiple react context? I mean i know the spaghetti that can occur where you need to update two different parts in a state when an action occurs. But i always feel such applications have a design flaw. If you have two contexts and need to update both for an action then maybe they should be one context? 

I often feel apps get really complicated in redux because redux allows you to listen to every state change in a reducer. This can lead to bugs. 

The real question. Why couldnt i just make a context for each bounded context (different terms here) and have the consumers consume and update as many contexts they like? For ex if a component wants to update user details, Theme, orders, messages, etc etc. With hooks its simple to make a context and
just consume it. But is there a down side or limit of having 30-40 contexts? And why? They are more isolated from each other than reducers and reducer state in redux.

**Comment by jarlah** [comment]
The obvious elephant in the room is that by having multiple contexts you must provide them all in a big badly nested form. But that should be solved simply by making a Providers component that take an array of context information. Or something. Like an array of objects with context object, initial value and etc

**Comment by dai-shi** [comment]
Let me clarify a few things as a start.

The major internal difference is how it uses contexts.
- react-context-global-state uses multiple contexts and works >= react 16.3
- react-hooks-global-state uses a single context with observedBits, provides hooks and works >= react 16.8

We don't know how many contexts it can have, but if we add more it should slow down (I hope it's linear.) I read a note somewhere that `observedBits` is very efficient, and it is so because of bitwise operations. However, `observedBits` works only up to 31 items in our implementation. And, `observedBits` is not documented, not stable, and can be replaced in the future.

As for hooks API, there are two styles: setState style is for those who want simple API, and reducer style is for those who want redux-like API. In your mindset, I'd recommend the setState style.

**Comment by jarlah** [comment]
I think what is my biggest problem with redux like way of developing react is the fact that almost everyone i have met that uses redux stores everything in redux. Thats completely unnecessary and creates many bugs. With react and hooks its simple to make reusable async calls as first class citizens.

So. I am using your hooks library and it works wonders for state like auth context and other need to be global state. But otherwise. I dont any longer see the need to avoid state. And i am using local async state update logic inside hooks or functions. Guess im getting to old for this one truth and one state.

**Comment by dai-shi** [comment]
I'm not sure if I answered all the questions but let me continue as a general topic.
As we now have hooks and contexts, I would use them without redux for small apps.
Redux is powerful when you need to separate logic (reducers) and actions, which, I think, means for large apps with many developers.
For me, Redux alternative is not hooks and context, but apollo-client. If someone is using Redux only for remote data management, it's going to be a good option.

**Comment by jarlah** [comment]
I like how my pattern here is going:

https://github.com/freeacs/freeacs-web/blob/master/src/App/shared/context/hooks.ts

I am actually hiding the fact that I am using any global state from the components. By hiding state management and async operations inside hooks, components only need to care about the stuff that come out of the hook. 

The only redux like thing I am using is in:

https://github.com/freeacs/freeacs-web/blob/master/src/App/state/index.ts

which is pretty minimal. I think, if I need something more in there I must have a good reason. 

Actually, I could potentially just have easily replaced useGlobalState with useContext inside my hooks.ts file above, and nothing would change. For such a small app, I agree with you, context or setState might be better

**Comment by jarlah** [comment]
But since we have an ongoing technical discussion, about hooks and api calls, should I wrap my api calls in useEffect? And trigger those effects based on something? I really wish I had a subject from rxjs here :P usually I just make a  `const [subject, setSubject] = setState<number>();` .. and updates it with Date.now() when I want an effect to run .. using `useEffect(() => ..., [subject])`

**Comment by dai-shi** [comment]
Calling async function in useEffect should be done with care. I'm not sure if you saw another library of mine `react-hooks-async`, which does the job, but it's not easy to implement. (It was easy to implement naively.) It can't replace rxjs as a whole but I have something in mind to use it instead of rxjs in a simple scenario, namely cancellation.

**Comment by jarlah** [comment]
Relating to rxjs. I have and old lib from 2017 that i have now rewamped with support for rxjs 6.

https://github.com/jarlah/react-rxjs

I have vague plans to also rewrite it from class components to hooks. Or otherwise find a cool way to make it work with hooks.

**Comment by jarlah** [comment]
https://github.com/jarlah/react-rxjs-hook

Done.  :) 

But anyway, closing this now, we can continue unrelating discussions in closed issue :P

**Comment by nanxiaobei** [comment]
**react-easy-contexts**, A simple tool to add multiple React contexts easily.

https://github.com/nanxiaobei/react-easy-contexts

**Comment by dai-shi** [comment]
A possible solution to React context provider hell.

https://twitter.com/dai_shi/status/1174093787137630210
